name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          git zip unzip wget tar openjdk-17-jdk autoconf libtool pkg-config \
          zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake \
          libffi-dev libssl-dev python3-pip

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install cython buildozer kivy

    - name: Install Android SDK and dependencies
      run: |
        # Устанавливаем Android SDK и необходимые компоненты
        sudo apt-get install -y android-sdk
        export ANDROID_HOME=/usr/lib/android-sdk
        export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/30.0.3:$PATH

        # Устанавливаем необходимые Build Tools
        sdkmanager "build-tools;30.0.3"
        sdkmanager "platforms;android-30"
        sdkmanager "platform-tools"
        sdkmanager "tools"
        sdkmanager "ndk;21.4.7075529"
        
        # Путь до sdkmanager
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH

    - name: Install Apache Ant
      run: |
        wget https://archive.apache.org/dist/ant/binaries/apache-ant-1.9.4-bin.tar.gz
        tar -xvzf apache-ant-1.9.4-bin.tar.gz
        sudo mv apache-ant-1.9.4 /opt/
        if [ ! -f /usr/bin/ant ]; then
          sudo ln -s /opt/apache-ant-1.9.4/bin/ant /usr/bin/ant
        fi

    - name: Initialize buildozer
      run: buildozer init || true

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: translator-apk
        path: bin/*.apk
