name: Build APK
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Update package lists with retry
      run: |
        # Retry apt update multiple times to handle temporary repository issues
        for i in {1..3}; do
          if sudo apt update; then
            break
          else
            echo "apt update failed, retrying in 10 seconds... ($i/3)"
            sleep 10
          fi
        done
        
    - name: Install system dependencies with retry and alternatives
      run: |
        # Install dependencies with retry mechanism and alternative repositories
        sudo apt install -y --fix-missing \
          git zip unzip wget tar openjdk-17-jdk autoconf libtool pkg-config \
          zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake \
          libffi-dev libssl-dev python3-pip python3-venv || \
        sudo apt install -y --fix-missing --no-install-recommends \
          git zip unzip wget tar openjdk-17-jdk autoconf libtool pkg-config \
          zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake \
          libffi-dev libssl-dev python3-pip python3-venv
          
    - name: Set up Python environment
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install --user cython
        
    - name: Install Buildozer and dependencies
      run: |
        python3 -m pip install --user buildozer
        python3 -m pip install --user kivy kivymd plyer
        
    - name: Set up Android development environment
      run: |
        # Create Android SDK directory
        mkdir -p $HOME/android-sdk
        export ANDROID_HOME=$HOME/android-sdk
        export ANDROID_SDK_ROOT=$ANDROID_HOME
        
        # Download and install Android command line tools
        cd $HOME
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-9477386_latest.zip
        
        # Properly organize the command line tools
        mkdir -p $ANDROID_HOME/cmdline-tools/latest
        mv cmdline-tools/* $ANDROID_HOME/cmdline-tools/latest/
        rmdir cmdline-tools
        
        # Set up environment variables
        echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$ANDROID_HOME" >> $GITHUB_ENV
        echo "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/30.0.3" >> $GITHUB_PATH
        
    - name: Accept Android SDK licenses and install components
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;30.0.3"
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-30"
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools"
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "ndk;21.4.7075529"
        
    - name: Install Apache Ant
      run: |
        cd $HOME
        wget https://archive.apache.org/dist/ant/binaries/apache-ant-1.10.12-bin.tar.gz
        tar -xzf apache-ant-1.10.12-bin.tar.gz
        export ANT_HOME=$HOME/apache-ant-1.10.12
        echo "ANT_HOME=$ANT_HOME" >> $GITHUB_ENV
        echo "$ANT_HOME/bin" >> $GITHUB_PATH
        
    - name: Check project structure and create main.py if needed
      run: |
        echo "Checking project structure..."
        ls -la
        
        # Check if main.py exists, create a simple one if it doesn't
        if [ ! -f main.py ]; then
          echo "Creating basic main.py file..."
          cat > main.py << 'EOF'
        from kivy.app import App
        from kivy.uix.label import Label
        from kivy.uix.boxlayout import BoxLayout
        from kivy.uix.button import Button
        
        class TranslatorApp(App):
            def build(self):
                layout = BoxLayout(orientation='vertical', padding=10, spacing=10)
                
                label = Label(text='Translator App', 
                             font_size='20sp',
                             size_hint=(1, 0.5))
                
                button = Button(text='Translate', 
                               size_hint=(1, 0.5))
                
                layout.add_widget(label)
                layout.add_widget(button)
                
                return layout
        
        if __name__ == '__main__':
            TranslatorApp().run()
        EOF
        fi
        
        # Check buildozer.spec
        if [ ! -f buildozer.spec ]; then
          echo "buildozer.spec not found, initializing..."
          buildozer init
        fi
        
        echo "Project files:"
        ls -la
        
    - name: Initialize buildozer configuration
      run: |
        # Ensure buildozer.spec exists and is configured properly
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi
        
    - name: Configure buildozer for CI environment
      run: |
        # Update buildozer.spec for CI environment
        sed -i 's/title = My Application/title = Translator App/' buildozer.spec
        sed -i 's/package.name = myapp/package.name = translator/' buildozer.spec
        sed -i 's/package.domain = org.example/package.domain = com.translator/' buildozer.spec
        
        # Set Android SDK and NDK paths
        sed -i 's/#android.sdk_path =.*/android.sdk_path = \/home\/runner\/android-sdk/' buildozer.spec
        sed -i 's/#android.ndk_path =.*/android.ndk_path = \/home\/runner\/android-sdk\/ndk\/21.4.7075529/' buildozer.spec
        sed -i 's/#android.ant_path =.*/android.ant_path = \/home\/runner\/apache-ant-1.10.12\/bin\/ant/' buildozer.spec
        
        # Set architecture and API levels
        sed -i 's/#android.archs = arm64-v8a, armeabi-v7a/android.archs = arm64-v8a, armeabi-v7a/' buildozer.spec
        sed -i 's/#android.api = 28/android.api = 30/' buildozer.spec
        sed -i 's/#android.minapi = 21/android.minapi = 21/' buildozer.spec
        sed -i 's/#android.ndk_api = 21/android.ndk_api = 21/' buildozer.spec
        
        # Ensure requirements include kivy
        sed -i 's/requirements = python3,kivy/requirements = python3,kivy,kivymd/' buildozer.spec
        
        echo "Updated buildozer.spec:"
        cat buildozer.spec | grep -E "(title|package|android\.|requirements)"
        
    - name: Build APK with detailed logging
      run: |
        echo "Starting buildozer android debug..."
        buildozer android debug --verbose
        
    - name: Find and list generated APK files
      run: |
        echo "Searching for APK files..."
        find . -name "*.apk" -type f -exec ls -la {} \;
        echo "Contents of bin directory:"
        ls -la bin/ 2>/dev/null || echo "bin directory does not exist"
        echo "Contents of .buildozer directory structure:"
        find .buildozer -name "*.apk" -type f 2>/dev/null || echo "No APK files found in .buildozer"
        
    - name: Copy APK to bin directory
      run: |
        mkdir -p bin
        # Find APK files and copy them to bin directory
        if find .buildozer -name "*.apk" -type f | head -1 | xargs -I {} cp {} bin/ 2>/dev/null; then
            echo "APK copied to bin directory successfully"
            ls -la bin/
        else
            echo "No APK file found to copy"
            exit 1
        fi
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: translator-apk
        path: bin/*.apk
        if-no-files-found: error
